[package]
name = "hexapod-wasm"
version = "0.1.0"
edition = "2021"
description = "WTE Hexapod â€” Interactive WebAssembly Demo"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
